#!/usr/bin/env node
// Copies the generated data out of the profile repo into a plain script the
// page can load with a <script> tag.
//
// Deliberately not fetch(). A script tag works on file:// for local preview,
// costs no round trip, and cannot fail halfway through rendering. The page has
// no build step of its own beyond this.

import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const SRC = process.env.PROFILE_REPO || join(HERE, '..', 'gh-profile', 'data');

const load = (name, required = true) => {
  const p = join(SRC, name);
  if (!existsSync(p)) {
    if (required) throw new Error(`missing ${p}. Run the profile repo generators first.`);
    return null;
  }
  return JSON.parse(readFileSync(p, 'utf8'));
};

const stats = load('stats.json');
const bench = load('bench.json', false);
const projects = load('projects.json', false);

// Trim what the page does not use. The full calendar and per-repo topics are
// dead weight on the wire and the page never reads them.
const slim = {
  generatedAt: stats.generatedAt,
  graphqlCost: stats.graphqlCost,
  tz: stats.tz,
  profile: stats.profile,
  repos: stats.repos,
  contributions: {
    lastYear: stats.contributions.lastYear,
    activeDays: stats.contributions.activeDays,
    trackedDays: stats.contributions.trackedDays,
    longestStreak: stats.contributions.longestStreak,
    currentStreak: stats.contributions.currentStreak,
  },
  languages: stats.languages,
  languageTotalBytes: stats.languageTotalBytes,
  rhythm: stats.rhythm,
  topRepos: stats.topRepos.map(({ topics, ...r }) => r),
  latestCommit: stats.latestCommit,
  recentCommits: stats.recentCommits,
};

const out = `// Generated by build.mjs from the profile repo. Do not edit by hand.
window.SITE = ${JSON.stringify({ stats: slim, bench, projects })};
`;

mkdirSync(join(HERE, 'data'), { recursive: true });
writeFileSync(join(HERE, 'data', 'site-data.js'), out);
// .nojekyll stops GitHub Pages running the content through Jekyll, which
// would otherwise ignore any path starting with an underscore.
writeFileSync(join(HERE, '.nojekyll'), '');

console.log(`data/site-data.js  ${(out.length / 1024).toFixed(1)} KB`
  + `  (${slim.topRepos.length} repos, ${slim.languages.length} languages`
  + `${bench ? `, ${bench.results.length} benchmarks` : ', no benchmarks'})`);
