import { chromium } from 'playwright';
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1400, height: 900 } });
const errs = [];
p.on('pageerror', e => errs.push('PAGEERROR ' + e.message));
p.on('console', m => { if (m.type()==='error' && !/favicon|WebGL|GL Driver/i.test(m.text())) errs.push(m.text()); });
const base = 'https://ubhayaab.github.io';
await p.goto(base + '/', { waitUntil: 'load' });
await p.waitForTimeout(4000);
const check = (n,c,d='') => console.log(`${c?'PASS':'FAIL'} ${n}${d?'  '+d:''}`);
check('live: games', await p.locator('#arcade-grid [data-play]').count() === 29, String(await p.locator('#arcade-grid [data-play]').count()));
check('live: categories', await p.locator('.cat-bar [data-cat]').count() === 8);
check('live: topnav', await p.locator('#topnav').isVisible());
check('live: boot gone', await p.locator('#boot').count() === 0);
await p.goto(base + '/#/consult', { waitUntil: 'load' }); await p.waitForTimeout(3500);
check('live: consult', (await p.locator('#consult .dos-title').textContent()) === 'Work with me');
await p.goto(base + '/#/vision/nuclear', { waitUntil: 'load' }); await p.waitForTimeout(3500);
check('live: dossier', (await p.locator('#dossier .dos-title').textContent()) === 'Nuclear energy');
await p.screenshot({ path: 'shots/v/live-dossier.png' });
const r404 = await p.goto(base + '/nope-not-here');
check('live: 404 page', (await p.locator('.lost h1').count()) === 1, 'status ' + r404.status());
console.log(errs.length ? 'ERRORS: '+[...new Set(errs)].slice(0,4).join(' | ') : 'no console errors');
await b.close();
