import { chromium } from 'playwright';
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1400, height: 900 } });
await p.goto('http://127.0.0.1:4199/', { waitUntil: 'load' });
await p.waitForTimeout(3000);
await p.evaluate(() => localStorage.setItem('theme','light'));
await p.reload({ waitUntil: 'load' });
await p.waitForTimeout(3000);
await p.evaluate(() => document.querySelector('#who').scrollIntoView());
await p.waitForTimeout(900);
await p.screenshot({ path: 'shots/v/light-who.png' });
await p.evaluate(() => document.querySelector('#work').scrollIntoView());
await p.waitForTimeout(900);
await p.screenshot({ path: 'shots/v/light-work.png' });
await p.evaluate(() => localStorage.setItem('theme','dark'));
await p.reload({ waitUntil: 'load' });
await p.waitForTimeout(3000);
await p.evaluate(() => document.querySelector('#who').scrollIntoView());
await p.waitForTimeout(900);
await p.screenshot({ path: 'shots/v/dark-who.png' });
await b.close();
